### ISSUE TITLE
Logic of nested condition AND

### ISSUE THREAD

**Issue by pmbert** [maros/Zway-ConditionSwitch#3]
What's the logic behind nested conditions?
What I want to do:
if device1=on AND device2=on then switch = on
What I tried first:
Nested Conditions=AND, device1=on, device2=on, switch=on
In this case it is only switched on if both devices are off
What is working in my sense:
Nested Conditions=AND, device1=off, device2=off, switch=on
But is this the right logic?

Software info
Firmware version    v2.2.3
UI version  1.4.3
Capabilities:   Slm
ConditionSwitch 1.09

**Comment by maros** [comment]
fixed in 1.10
